---
title: "hw_5"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE}
library(tidyverse)
```

## Задание 5.1.1

```{r}
movies <- read_csv('https://raw.githubusercontent.com/r-classes/ds4dh-hw5-akryukov39/master/data/MovieLens_films.csv?token=ANEYUWH2BYJDOX7P4CZRJQK63T4LC')

movies %>% 
  mutate(prediction = predict(fit)) %>% 
  ggplot(aes(year, mean_rating, color = genres))+
  geom_point() +
  geom_smooth(method = "lm") +
  labs(caption = "data from MovieLens")
```

## Задание 5.1.2

```{r}
fit <- lm(mean_rating ~ year+ genres, data = movies)
summary(fit)
```

mean rating (comedy) = 9.7547 - 0.0031 * year
...
  
Укажите наибольший свободный член

...

## Задание 5.1.3

```{r}
library(ggeffects)
plot(ggpredict(fit, terms = c("year","genres")))
```

## Задание 5.1.4

Укажите предсказания модели для комедий в 2007, 2011 и 2018
```{r}

```


## Задание 5.2

## Задание 5.2.1

```{r}
```

## Задание 5.2.2

```{r}
```

average rating (bluffing) = ... * owned
...

Укажите наибольший свободный член

...

## Задание 5.2.3

```{r}
```

## Задание 5.2.4

```{r}
```

## Задание 5.3

```{r}
```

## Задание 5.4.1

```{r}
library(statcheck)
```

## Задание 5.4.2

```{r}
```

## Задание 5.4.3

```{r}
```

